language: r

before_install:
  - cd /home/travis/build/courtiol/IsoriX_project/IsoriX/
  
cache: packages

r:
  - release
  - devel
  
r_check_args: 
  --as-cran

r_packages:
  - rgdal
  - covr
  
after_success:
  - Rscript -e 'library(covr); codecov(type = "examples")'
