language: r

before_install:
  #- sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install riak
  # 4. add GIS repos
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt update -y
  # 6. install gdal
  - sudo apt install -y gdal-bin libgdal-dev python-gdal python3-gdal
  ## go to the IsoirX folder
  - cd IsoriX

before_script:
  - Rscript -e 'install.packages("rgdal", type = "source")'

cache: packages

r:
  - release
  - devel
  
r_check_args: 
  --as-cran

r_packages:
  - covr
  
after_success:
  - Rscript -e 'library(covr); codecov(type = "examples")'
