language: r

cache: packages

before_install:
 - cd /home/travis/build/courtiol/IsoriX_project/IsoriX/

r:
  - oldrel
  - release
  - devel
  
r_check_args: 
  --as-cran

r_packages:
  - covr
  - Cairo
  - GISTools
  - lattice
  - magick
  - maps
  - maptools
  - RandomFields
  - rgeos
  - rgl

addons:
  apt:
    packages:
      - ghostscript
  
after_success:
  - Rscript -e 'library(covr); codecov(type = "examples")'