language: r

before_install:
  # install gdal and proj4 from ubuntugis ppa (from github.com/jannes-m/RQGIS/)
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt update -y
  - sudo apt upgrade -y
  - sudo apt-get remove -y postgresql-9.*
  - sudo apt install gdal-bin libgdal-dev python-gdal python3-gdal
  # go to the IsoirX folder
  - cd IsoriX

before_script:
  - Rscript -e 'install.packages("rgdal", type = "source")'

cache: packages

r:
  - release
  - devel
  
r_check_args: 
  --as-cran

r_packages:
  - covr
  
after_success:
  - Rscript -e 'library(covr); codecov(type = "examples")'
